[program:nwc-messaging-notifications]
directory=/home/newworldcargo/web/admin.newworldcargo.com/public_html
command=/usr/bin/php artisan queue:work messaging --queue=notifications --sleep=1 --rest=1 --timeout=45 --memory=128 --max-jobs=500 --max-time=3600
user=newworldcargo
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=130
redirect_stderr=true
stdout_logfile=/home/newworldcargo/web/admin.newworldcargo.com/public_html/storage/logs/messaging-notifications.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
