@extends('cargo::adminLte.layouts.master')

@section('content')
<div class="container-fluid py-3">
    <div class="d-flex justify-content-between align-items-start mb-3">
        <div><h3 class="mb-1">Import preview & column mapping</h3><p class="text-muted mb-0">{{ $batch->original_filename }} · Nothing is written until you confirm this import.</p></div>
        <a class="btn btn-outline-secondary" href="{{ route('consignment.index') }}">Back to consignments</a>
    </div>
    @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
    @if($batch->status === 'completed')<div class="alert alert-success"><strong>Import completed.</strong> {{ $batch->result['imported'] ?? 0 }} shipment(s) were created. This batch cannot be run again.</div>@endif
    <form method="POST" action="{{ route('consignment.import.preview.update', $batch->uuid) }}">
        @csrf
        <div class="card mb-3"><div class="card-body">
            <div class="row">
                <div class="col-md-3 form-group"><label>Sheet</label><select name="selected_sheet" class="form-control" onchange="this.form.submit()">@foreach($sheets as $sheet)<option value="{{ $sheet }}" @selected($batch->selected_sheet === $sheet)>{{ $sheet }}</option>@endforeach</select></div>
                <div class="col-md-2 form-group"><label>Header row</label><input name="header_row" type="number" min="1" value="{{ $batch->header_row }}" class="form-control"></div>
                <div class="col-md-2 form-group"><label>Data starts at row</label><input name="data_start_row" type="number" min="1" value="{{ $batch->data_start_row }}" class="form-control"></div>
                <div class="col-md-3 form-group"><label>Operational branch <span class="text-danger">*</span></label><select name="branch_id" class="form-control"><option value="">Choose branch before confirming</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected($batch->branch_id == $branch->id)>{{ $branch->name }}</option>@endforeach</select></div>
                <div class="col-md-2 d-flex align-items-end form-group"><button class="btn btn-primary btn-block" @disabled($batch->status === 'completed')>Refresh preview</button></div>
            </div>
            <div class="row"><div class="col-md-3 form-group"><label>Origin country <span class="text-danger">*</span></label><select name="from_country_id" class="form-control"><option value="">Select</option>@foreach($countries as $country)<option value="{{ $country->id }}" @selected($batch->from_country_id == $country->id)>{{ $country->name }}</option>@endforeach</select></div><div class="col-md-3 form-group"><label>Origin state <span class="text-danger">*</span></label><select name="from_state_id" class="form-control"><option value="">Select</option>@foreach($states as $state)<option value="{{ $state->id }}" @selected($batch->from_state_id == $state->id)>{{ $state->name }}</option>@endforeach</select></div><div class="col-md-3 form-group"><label>Destination country <span class="text-danger">*</span></label><select name="to_country_id" class="form-control"><option value="">Select</option>@foreach($countries as $country)<option value="{{ $country->id }}" @selected($batch->to_country_id == $country->id)>{{ $country->name }}</option>@endforeach</select></div><div class="col-md-3 form-group"><label>Destination state <span class="text-danger">*</span></label><select name="to_state_id" class="form-control"><option value="">Select</option>@foreach($states as $state)<option value="{{ $state->id }}" @selected($batch->to_state_id == $state->id)>{{ $state->name }}</option>@endforeach</select></div></div>
        </div></div>
        <div class="card mb-3"><div class="card-header"><strong>Raw spreadsheet preview</strong><span class="text-muted ml-2">Rows and column letters are preserved so you can select the real heading row.</span></div><div class="card-body p-0 table-responsive" style="max-height:360px"><table class="table table-sm table-bordered mb-0"><thead><tr><th>Row</th>@foreach(array_keys($header) as $column)<th>{{ $column }}</th>@endforeach</tr></thead><tbody>@foreach($rows as $row)<tr class="{{ $row->spreadsheet_row == $batch->header_row ? 'table-info' : '' }}"><td><strong>{{ $row->spreadsheet_row }}</strong></td>@foreach(array_keys($header) as $column)<td>{{ $row->raw_values[$column] ?? '' }}</td>@endforeach</tr>@endforeach</tbody></table></div></div>
        <div class="card mb-3"><div class="card-header"><strong>Map spreadsheet columns</strong><span class="text-muted ml-2">Phone number is required and must match an existing customer account.</span></div><div class="card-body"><div class="row">
            @foreach($fields as $field => $definition)<div class="col-md-4 form-group"><label>{{ $definition['label'] }} @if($definition['required'])<span class="text-danger">*</span>@endif</label><select class="form-control" name="mapping[{{ $field }}]"><option value="">Do not import</option>@foreach($header as $column => $heading)<option value="{{ $column }}" @selected(($batch->mappings[$field] ?? '') === $column)>Column {{ $column }} — {{ $heading ?: '(blank)' }}</option>@endforeach</select></div>@endforeach
        </div></div></div>
        <div class="card"><div class="card-header d-flex justify-content-between"><strong>Mapped data preview</strong><span>Detected: {{ $batch->summary['detected'] ?? 0 }} · Valid: {{ $batch->summary['valid'] ?? 0 }} · Invalid: {{ $batch->summary['invalid'] ?? 0 }} · Duplicates: {{ $batch->summary['duplicate'] ?? 0 }}</span></div><div class="card-body p-0 table-responsive"><table class="table table-sm table-hover mb-0"><thead><tr><th>Import</th><th>Row</th><th>Status</th><th>Parcel code</th><th>Consignee</th><th>Phone</th><th>Destination</th><th>Issues</th></tr></thead><tbody>
            @foreach($rows->where('spreadsheet_row','>=',$batch->data_start_row) as $row)<tr><td><input type="checkbox" name="included[{{ $row->id }}]" value="1" @checked($row->included) @disabled($batch->status === 'completed')></td><td>{{ $row->spreadsheet_row }}</td><td><span class="badge badge-{{ $row->status === 'valid' ? 'success' : ($row->status === 'duplicate' ? 'warning' : ($row->status === 'invalid' ? 'danger' : 'secondary')) }}">{{ ucfirst($row->status) }}</span></td><td>{{ $row->mapped_values['hawb_number'] ?? '—' }}</td><td>{{ $row->mapped_values['consignee_name'] ?? '—' }}</td><td>{{ $row->mapped_values['phone'] ?? '—' }}</td><td>{{ $row->mapped_values['destination'] ?? '—' }}</td><td class="small text-danger">{{ implode(' ', $row->validation_errors ?? []) ?: implode(' ', $row->validation_warnings ?? []) }}</td></tr>@endforeach
        </tbody></table></div></div>
        @if($batch->status !== 'completed')<div class="mt-3 text-right"><button class="btn btn-outline-primary">Save mapping & selected rows</button></div>@endif
    </form>
    @if($batch->status !== 'completed')<form method="POST" action="{{ route('consignment.import.confirm', $batch->uuid) }}" class="mt-3 text-right">@csrf<button class="btn btn-success" onclick="return confirm('Create the selected valid shipments now? This cannot be undone from this screen.')">Confirm import ({{ $batch->summary['selected'] ?? 0 }} selected)</button></form>@endif
</div>
@endsection
